url: https://rundowntown.github.io
baseurl: /Gallop

######## Site settings ########
title: Gallop
email: contact@gallopstartup.com
description: "Gallop is an innovative startup building analytics and visualization tools to bridge policy and public sentiment."

######## Team names, titles and social links ########
people:
- name: Daniel Forcade
  pic: daniel
  position: Co-Founder & Data Architect
  social:
    - title: twitter
      url: 
    - title: github
      url: https://github.com/rundowntown

- name: Steven Wasserman
  pic: steven
  position: Co-Founder & Technical Lead
  social:
    - title: linkedin
      url: 
    - title: github
      url: 

- name: Ryan Hopkins
  pic: ryan
  position: Co-Founder & Machine Learning Engineer
  social:
    - title: github
      url: 
    - title: twitter
      url: 

- name: Hanna Bodnar
  pic: hanna
  position: Co-Founder & Front-End Developer
  social:
    - title: linkedin
      url: 
    - title: instagram
      url: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: https://github.com/The-Policy-Posse

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
